application: auto
version: auto
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on

handlers:
- url: /cron/.*
  script: server.app
  secure: always
  login: admin

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /people/.*
  script: server.app
  secure: always
  login: required

- url: /.*
  script: server.app
  secure: always
  login: required
